version: "2"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    restart: always
    environment:
       - GIN_MODE=release
    volumes:
      - ./data:/go/src/github.com/spacepatcher/softrace/data
    ports:
    - "127.0.0.1:8001:8001"
